import type {
  AcquisitionSource,
  Device,
  Merchant,
  Offer,
  RawIngestRecord,
  SavedScenario,
} from "@/lib/schema";

export const devices: Device[] = [
  {
    id: "dev_iphone_13_128",
    slug: "iphone-13-128",
    brand: "Apple",
    model: "iPhone 13 128GB",
    year: 2021,
    storageVariants: ["128GB", "256GB"],
    msrp: 799,
    imageUrl: "/devices/iphone-13.svg",
    releaseDate: "2021-09-24",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair", "cracked"],
    deprecated: false,
    notes: "Strong mid-cycle trade-in anchor with wide carrier acceptance.",
  },
  {
    id: "dev_iphone_14_pro_256",
    slug: "iphone-14-pro-256",
    brand: "Apple",
    model: "iPhone 14 Pro 256GB",
    year: 2022,
    storageVariants: ["128GB", "256GB", "512GB"],
    msrp: 1099,
    imageUrl: "/devices/iphone-14-pro.svg",
    releaseDate: "2022-09-16",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair"],
    deprecated: false,
    notes: "Higher-value Apple trade-in with premium promo eligibility.",
  },
  {
    id: "dev_iphone_16_pro_256",
    slug: "iphone-16-pro-256",
    brand: "Apple",
    model: "iPhone 16 Pro 256GB",
    year: 2025,
    storageVariants: ["128GB", "256GB", "512GB"],
    msrp: 1099,
    imageUrl: "/devices/iphone-16-pro.svg",
    releaseDate: "2025-09-19",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair"],
    deprecated: false,
    notes: "Premium target device used across Apple upgrade comparisons.",
  },
  {
    id: "dev_galaxy_s23_128",
    slug: "galaxy-s23-128",
    brand: "Samsung",
    model: "Galaxy S23 128GB",
    year: 2023,
    storageVariants: ["128GB", "256GB"],
    msrp: 799,
    imageUrl: "/devices/galaxy-s23.svg",
    releaseDate: "2023-02-17",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair", "cracked"],
    deprecated: false,
    notes: "Consistently promoted by carriers for flagship upgrades.",
  },
  {
    id: "dev_galaxy_s25_ultra_256",
    slug: "galaxy-s25-ultra-256",
    brand: "Samsung",
    model: "Galaxy S25 Ultra 256GB",
    year: 2025,
    storageVariants: ["256GB", "512GB"],
    msrp: 1299,
    imageUrl: "/devices/galaxy-s25-ultra.svg",
    releaseDate: "2025-02-07",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair"],
    deprecated: false,
    notes: "Primary Samsung flagship target in seeded data.",
  },
  {
    id: "dev_pixel_7_128",
    slug: "pixel-7-128",
    brand: "Google",
    model: "Pixel 7 128GB",
    year: 2022,
    storageVariants: ["128GB", "256GB"],
    msrp: 599,
    imageUrl: "/devices/pixel-7.svg",
    releaseDate: "2022-10-13",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair", "cracked"],
    deprecated: false,
    notes: "Often undervalued directly but useful in certain promos.",
  },
  {
    id: "dev_pixel_6a_128",
    slug: "pixel-6a-128",
    brand: "Google",
    model: "Pixel 6a 128GB",
    year: 2022,
    storageVariants: ["128GB"],
    msrp: 449,
    imageUrl: "/devices/pixel-6a.svg",
    releaseDate: "2022-07-28",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair", "cracked"],
    deprecated: false,
    notes: "Classic arbitrage candidate due to low used-market acquisition cost.",
  },
  {
    id: "dev_pixel_9_pro_256",
    slug: "pixel-9-pro-256",
    brand: "Google",
    model: "Pixel 9 Pro 256GB",
    year: 2024,
    storageVariants: ["128GB", "256GB", "512GB"],
    msrp: 1099,
    imageUrl: "/devices/pixel-9-pro.svg",
    releaseDate: "2024-08-22",
    category: "smartphone",
    supportedConditions: ["mint", "good", "fair"],
    deprecated: false,
    notes: "Pixel flagship target for Google Store and carrier deals.",
  },
];

export const merchants: Merchant[] = [
  {
    id: "att",
    slug: "att",
    name: "AT&T",
    type: "carrier",
    logoUrl: "/merchants/att.svg",
    siteUrl: "https://www.att.com",
    affiliateCapable: false,
    defaultLinkType: "direct",
    trustScore: 0.72,
    notes: "Often strong headline values with installment and plan requirements.",
  },
  {
    id: "verizon",
    slug: "verizon",
    name: "Verizon",
    type: "carrier",
    logoUrl: "/merchants/verizon.svg",
    siteUrl: "https://www.verizon.com",
    affiliateCapable: false,
    defaultLinkType: "direct",
    trustScore: 0.74,
    notes: "Broad flagship support, but frequent new-line gating.",
  },
  {
    id: "tmobile",
    slug: "tmobile",
    name: "T-Mobile",
    type: "carrier",
    logoUrl: "/merchants/tmobile.svg",
    siteUrl: "https://www.t-mobile.com",
    affiliateCapable: false,
    defaultLinkType: "direct",
    trustScore: 0.76,
    notes: "Aggressive promo values with bill-credit structures.",
  },
  {
    id: "apple",
    slug: "apple",
    name: "Apple",
    type: "manufacturer",
    logoUrl: "/merchants/apple.svg",
    siteUrl: "https://www.apple.com",
    affiliateCapable: false,
    defaultLinkType: "direct",
    trustScore: 0.92,
    notes: "Reliable direct trade-in values with straightforward checkout.",
  },
  {
    id: "best-buy",
    slug: "best-buy",
    name: "Best Buy",
    type: "retailer",
    logoUrl: "/merchants/bestbuy.svg",
    siteUrl: "https://www.bestbuy.com",
    affiliateCapable: true,
    defaultLinkType: "affiliate",
    trustScore: 0.86,
    notes: "Useful middle ground between carrier promos and direct trade-ins.",
  },
  {
    id: "google-store",
    slug: "google-store",
    name: "Google Store",
    type: "manufacturer",
    logoUrl: "/merchants/google-store.svg",
    siteUrl: "https://store.google.com",
    affiliateCapable: false,
    defaultLinkType: "direct",
    trustScore: 0.89,
    notes: "Transparent Pixel upgrades, often with store credit.",
  },
  {
    id: "ebay",
    slug: "ebay",
    name: "eBay",
    type: "marketplace",
    logoUrl: "/merchants/ebay.svg",
    siteUrl: "https://www.ebay.com",
    affiliateCapable: true,
    defaultLinkType: "affiliate",
    trustScore: 0.68,
    notes: "Acquisition marketplace used for realistic buy-first arbitrage estimates.",
  },
];

export const offers: Offer[] = [
  {
    id: "offer_att_iphone16pro_1000",
    slug: "att-iphone-16-pro-up-to-1000",
    merchantId: "att",
    carrierName: "AT&T",
    targetDevice: "iPhone 16 Pro 256GB",
    targetDeviceSlug: "iphone-16-pro-256",
    acceptedTradeInDevices: ["iphone-13-128", "iphone-14-pro-256", "pixel-7-128", "pixel-6a-128"],
    acceptedConditions: ["good", "fair", "mint"],
    tradeInType: "bill_credit",
    tradeInValue: 1000,
    monthlyCreditAmount: 27.78,
    months: 36,
    newLineRequired: false,
    installmentRequired: true,
    eligiblePlanRequired: true,
    onlineOnly: false,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: true,
    startDate: "2026-02-15",
    endDate: "2026-03-31",
    sourceUrl: "https://www.att.com/deals/iphone",
    sourceType: "verified",
    confidenceScore: 0.82,
    lastVerifiedAt: "2026-03-05",
    finePrintSummary: "Requires qualifying unlimited plan, 36-month installment, and eligible trade-in in good condition.",
    notes: "High headline value but delayed realization.",
  },
  {
    id: "offer_verizon_iphone16pro_830",
    slug: "verizon-iphone-16-pro-830",
    merchantId: "verizon",
    carrierName: "Verizon",
    targetDevice: "iPhone 16 Pro 256GB",
    targetDeviceSlug: "iphone-16-pro-256",
    acceptedTradeInDevices: ["iphone-13-128", "iphone-14-pro-256", "galaxy-s23-128"],
    acceptedConditions: ["mint", "good", "fair"],
    tradeInType: "bill_credit",
    tradeInValue: 830,
    monthlyCreditAmount: 23.06,
    months: 36,
    newLineRequired: true,
    installmentRequired: true,
    eligiblePlanRequired: true,
    onlineOnly: true,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: true,
    startDate: "2026-02-20",
    endDate: "2026-03-22",
    sourceUrl: "https://www.verizon.com/deals/iphone",
    sourceType: "verified",
    confidenceScore: 0.79,
    lastVerifiedAt: "2026-03-04",
    finePrintSummary: "Top value requires a new line on Unlimited Ultimate with device payment agreement.",
    notes: "Good value but heavy new-line friction.",
  },
  {
    id: "offer_tmo_galaxy_s25_1000",
    slug: "tmobile-galaxy-s25-ultra-1000",
    merchantId: "tmobile",
    carrierName: "T-Mobile",
    targetDevice: "Galaxy S25 Ultra 256GB",
    targetDeviceSlug: "galaxy-s25-ultra-256",
    acceptedTradeInDevices: ["galaxy-s23-128", "iphone-13-128", "pixel-7-128", "pixel-6a-128"],
    acceptedConditions: ["good", "fair", "mint"],
    tradeInType: "bill_credit",
    tradeInValue: 1000,
    monthlyCreditAmount: 27.78,
    months: 36,
    newLineRequired: false,
    installmentRequired: true,
    eligiblePlanRequired: true,
    onlineOnly: false,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: true,
    startDate: "2026-02-10",
    endDate: "2026-03-28",
    sourceUrl: "https://www.t-mobile.com/offers/samsung-phone-deals",
    sourceType: "verified",
    confidenceScore: 0.84,
    lastVerifiedAt: "2026-03-05",
    finePrintSummary: "Requires Go5G Plus or Next and 36 monthly bill credits after trade-in validation.",
    notes: "Strong for Samsung loyalists, delayed value over time.",
  },
  {
    id: "offer_apple_iphone16pro_410",
    slug: "apple-iphone-16-pro-410",
    merchantId: "apple",
    carrierName: null,
    targetDevice: "iPhone 16 Pro 256GB",
    targetDeviceSlug: "iphone-16-pro-256",
    acceptedTradeInDevices: ["iphone-13-128", "iphone-14-pro-256", "galaxy-s23-128"],
    acceptedConditions: ["good", "fair", "mint", "cracked"],
    tradeInType: "instant",
    tradeInValue: 410,
    monthlyCreditAmount: null,
    months: null,
    newLineRequired: false,
    installmentRequired: false,
    eligiblePlanRequired: false,
    onlineOnly: false,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: false,
    startDate: "2026-01-10",
    endDate: "2026-04-15",
    sourceUrl: "https://www.apple.com/shop/trade-in",
    sourceType: "verified",
    confidenceScore: 0.94,
    lastVerifiedAt: "2026-03-05",
    finePrintSummary: "Straightforward Apple trade-in estimate applied instantly at checkout or as gift card.",
    notes: "Lower value but highest clarity and low lock-in risk.",
  },
  {
    id: "offer_bestbuy_iphone16pro_520",
    slug: "best-buy-iphone-16-pro-520",
    merchantId: "best-buy",
    carrierName: null,
    targetDevice: "iPhone 16 Pro 256GB",
    targetDeviceSlug: "iphone-16-pro-256",
    acceptedTradeInDevices: ["iphone-13-128", "iphone-14-pro-256", "galaxy-s23-128", "pixel-7-128"],
    acceptedConditions: ["mint", "good", "fair"],
    tradeInType: "store_credit",
    tradeInValue: 520,
    monthlyCreditAmount: null,
    months: null,
    newLineRequired: false,
    installmentRequired: false,
    eligiblePlanRequired: false,
    onlineOnly: true,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: false,
    startDate: "2026-02-01",
    endDate: "2026-03-18",
    sourceUrl: "https://www.bestbuy.com/site/mobile-cell-phones/trade-in/pcmcat1563302948687.c",
    sourceType: "verified",
    confidenceScore: 0.87,
    lastVerifiedAt: "2026-03-03",
    finePrintSummary: "Store credit applied instantly online, no line lock-in, limited to in-stock inventory.",
    notes: "Solid middle-ground offer for unlocked buyers.",
  },
  {
    id: "offer_google_pixel9pro_450",
    slug: "google-store-pixel-9-pro-450",
    merchantId: "google-store",
    carrierName: null,
    targetDevice: "Pixel 9 Pro 256GB",
    targetDeviceSlug: "pixel-9-pro-256",
    acceptedTradeInDevices: ["pixel-7-128", "pixel-6a-128", "iphone-13-128", "galaxy-s23-128"],
    acceptedConditions: ["mint", "good", "fair"],
    tradeInType: "store_credit",
    tradeInValue: 450,
    monthlyCreditAmount: null,
    months: null,
    newLineRequired: false,
    installmentRequired: false,
    eligiblePlanRequired: false,
    onlineOnly: true,
    inStoreOnly: false,
    unlockedRequired: true,
    activationRequired: false,
    startDate: "2026-02-18",
    endDate: "2026-03-25",
    sourceUrl: "https://store.google.com/tradein",
    sourceType: "verified",
    confidenceScore: 0.9,
    lastVerifiedAt: "2026-03-05",
    finePrintSummary: "Google Store credit estimate for unlocked Pixel checkout with mail-in trade-in.",
    notes: "Very clean unlocked path for Pixel buyers.",
  },
  {
    id: "offer_bestbuy_s25_600",
    slug: "best-buy-galaxy-s25-ultra-600",
    merchantId: "best-buy",
    carrierName: null,
    targetDevice: "Galaxy S25 Ultra 256GB",
    targetDeviceSlug: "galaxy-s25-ultra-256",
    acceptedTradeInDevices: ["galaxy-s23-128", "iphone-13-128", "pixel-7-128"],
    acceptedConditions: ["good", "fair", "mint"],
    tradeInType: "store_credit",
    tradeInValue: 600,
    monthlyCreditAmount: null,
    months: null,
    newLineRequired: false,
    installmentRequired: false,
    eligiblePlanRequired: false,
    onlineOnly: true,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: false,
    startDate: "2026-02-14",
    endDate: "2026-03-19",
    sourceUrl: "https://www.bestbuy.com/site/samsung-cell-phones",
    sourceType: "manual",
    confidenceScore: 0.78,
    lastVerifiedAt: "2026-03-02",
    finePrintSummary: "Manual offer entry combining trade-in credit and retailer savings for unlocked checkout.",
    notes: "Good value, slightly lower confidence due to manual verification.",
  },
  {
    id: "offer_att_pixel9pro_800",
    slug: "att-pixel-9-pro-800",
    merchantId: "att",
    carrierName: "AT&T",
    targetDevice: "Pixel 9 Pro 256GB",
    targetDeviceSlug: "pixel-9-pro-256",
    acceptedTradeInDevices: ["pixel-7-128", "pixel-6a-128", "iphone-13-128", "galaxy-s23-128"],
    acceptedConditions: ["good", "fair", "mint"],
    tradeInType: "bill_credit",
    tradeInValue: 800,
    monthlyCreditAmount: 22.22,
    months: 36,
    newLineRequired: false,
    installmentRequired: true,
    eligiblePlanRequired: true,
    onlineOnly: false,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: true,
    startDate: "2026-02-21",
    endDate: "2026-03-30",
    sourceUrl: "https://www.att.com/deals/google-pixel-phones",
    sourceType: "estimated",
    confidenceScore: 0.74,
    lastVerifiedAt: "2026-03-01",
    finePrintSummary: "Estimated value based on current promo terms; final tier may vary by trade-in assessment.",
    notes: "Good Pixel promo but estimated until manually re-verified.",
  },
  {
    id: "offer_tmo_iphone16pro_830",
    slug: "tmobile-iphone-16-pro-830",
    merchantId: "tmobile",
    carrierName: "T-Mobile",
    targetDevice: "iPhone 16 Pro 256GB",
    targetDeviceSlug: "iphone-16-pro-256",
    acceptedTradeInDevices: ["iphone-13-128", "iphone-14-pro-256", "galaxy-s23-128"],
    acceptedConditions: ["good", "fair", "mint"],
    tradeInType: "bill_credit",
    tradeInValue: 830,
    monthlyCreditAmount: 23.06,
    months: 36,
    newLineRequired: false,
    installmentRequired: true,
    eligiblePlanRequired: true,
    onlineOnly: false,
    inStoreOnly: false,
    unlockedRequired: false,
    activationRequired: true,
    startDate: "2026-02-25",
    endDate: "2026-03-31",
    sourceUrl: "https://www.t-mobile.com/offers/apple-iphone-deals",
    sourceType: "verified",
    confidenceScore: 0.83,
    lastVerifiedAt: "2026-03-05",
    finePrintSummary: "Requires premium plan and 36-month financing; value credited over time.",
    notes: "Less restrictive than Verizon, still delayed.",
  },
  {
    id: "offer_google_pixel9pro_300_cash",
    slug: "google-store-pixel-9-pro-300-instant",
    merchantId: "google-store",
    carrierName: null,
    targetDevice: "Pixel 9 Pro 256GB",
    targetDeviceSlug: "pixel-9-pro-256",
    acceptedTradeInDevices: ["pixel-7-128", "pixel-6a-128"],
    acceptedConditions: ["good", "fair", "mint", "cracked"],
    tradeInType: "cash",
    tradeInValue: 300,
    monthlyCreditAmount: null,
    months: null,
    newLineRequired: false,
    installmentRequired: false,
    eligiblePlanRequired: false,
    onlineOnly: true,
    inStoreOnly: false,
    unlockedRequired: true,
    activationRequired: false,
    startDate: "2026-02-05",
    endDate: "2026-04-10",
    sourceUrl: "https://store.google.com/tradein",
    sourceType: "verified",
    confidenceScore: 0.91,
    lastVerifiedAt: "2026-03-05",
    finePrintSummary: "Straight cash-equivalent trade-in estimate for eligible Pixels on unlocked checkout.",
    notes: "Lower headline value, highest immediacy.",
  },
];

export const acquisitionSources: AcquisitionSource[] = [
  {
    id: "acq_pixel6a_ebay_good",
    deviceId: "dev_pixel_6a_128",
    merchantId: "ebay",
    sourceType: "ebay",
    title: "Pixel 6a 128GB - Good unlocked (avg sold comps)",
    url: "https://www.ebay.com/sch/i.html?_nkw=pixel+6a+128gb+unlocked",
    affiliateUrl: "https://www.ebay.com/sch/i.html?_nkw=pixel+6a+128gb+unlocked&mkcid=1",
    estimatedPrice: 148,
    condition: "good",
    sellerRatingOrConfidence: 0.79,
    lastCheckedAt: "2026-03-05",
  },
  {
    id: "acq_pixel7_ebay_good",
    deviceId: "dev_pixel_7_128",
    merchantId: "ebay",
    sourceType: "ebay",
    title: "Pixel 7 128GB - Good unlocked (avg sold comps)",
    url: "https://www.ebay.com/sch/i.html?_nkw=pixel+7+128gb+unlocked",
    affiliateUrl: "https://www.ebay.com/sch/i.html?_nkw=pixel+7+128gb+unlocked&mkcid=1",
    estimatedPrice: 228,
    condition: "good",
    sellerRatingOrConfidence: 0.77,
    lastCheckedAt: "2026-03-05",
  },
  {
    id: "acq_iphone13_ebay_good",
    deviceId: "dev_iphone_13_128",
    merchantId: "ebay",
    sourceType: "ebay",
    title: "iPhone 13 128GB - Good unlocked (avg sold comps)",
    url: "https://www.ebay.com/sch/i.html?_nkw=iphone+13+128gb+unlocked",
    affiliateUrl: "https://www.ebay.com/sch/i.html?_nkw=iphone+13+128gb+unlocked&mkcid=1",
    estimatedPrice: 356,
    condition: "good",
    sellerRatingOrConfidence: 0.82,
    lastCheckedAt: "2026-03-05",
  },
  {
    id: "acq_galaxys23_bestbuy_fair",
    deviceId: "dev_galaxy_s23_128",
    merchantId: "best-buy",
    sourceType: "bestbuy",
    title: "Galaxy S23 128GB - Fair open-box estimate",
    url: "https://www.bestbuy.com/site/searchpage.jsp?st=galaxy+s23+open+box",
    affiliateUrl: "https://www.bestbuy.com/site/searchpage.jsp?st=galaxy+s23+open+box",
    estimatedPrice: 334,
    condition: "fair",
    sellerRatingOrConfidence: 0.75,
    lastCheckedAt: "2026-03-03",
  },
];

export const savedScenarios: SavedScenario[] = [
  {
    id: "scenario_1",
    userId: "demo_user",
    currentDevice: "iphone-13-128",
    targetDevice: "iphone-16-pro-256",
    condition: "good",
    preferences: {
      merchant: "best-buy",
      unlocked: "true",
    },
    resultSnapshot: "Best Buy unlocked path with $520 store credit ranked top for low risk.",
  },
  {
    id: "scenario_2",
    userId: "demo_user",
    currentDevice: "pixel-7-128",
    targetDevice: "galaxy-s25-ultra-256",
    condition: "good",
    preferences: {
      merchant: "tmobile",
      allowIntermediate: "true",
    },
    resultSnapshot: "Pixel 6a buy-first trade into T-Mobile promo created the best spread.",
  },
];

export const rawIngestRecords: RawIngestRecord[] = [
  {
    id: "raw_1",
    sourceName: "AT&T iPhone deals",
    sourceUrl: "https://www.att.com/deals/iphone",
    payload: "{\"promo\":\"up to 1000\"}",
    parsedAt: "2026-03-05T10:30:00.000Z",
    status: "parsed",
    errors: "",
  },
  {
    id: "raw_2",
    sourceName: "Best Buy trade-in grid",
    sourceUrl: "https://www.bestbuy.com/site/mobile-cell-phones/trade-in/pcmcat1563302948687.c",
    payload: "{\"grid\":\"manual import\"}",
    parsedAt: "2026-03-02T14:12:00.000Z",
    status: "pending",
    errors: "",
  },
];

export const topUpgradeComparisons = [
  {
    slug: "iphone-13-to-iphone-16-pro",
    oldDeviceSlug: "iphone-13-128",
    newDeviceSlug: "iphone-16-pro-256",
  },
  {
    slug: "pixel-7-to-pixel-9-pro",
    oldDeviceSlug: "pixel-7-128",
    newDeviceSlug: "pixel-9-pro-256",
  },
  {
    slug: "galaxy-s23-to-galaxy-s25-ultra",
    oldDeviceSlug: "galaxy-s23-128",
    newDeviceSlug: "galaxy-s25-ultra-256",
  },
] as const;
